import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { SetlistClient } from '../src/client.js';
import { registerUtilityTools } from '../src/tools/utilities.js';
import { createTestHarness } from './helpers.js';

/**
 * A CDN/WAF block is not a rejected API key (chrischall/mcp-host#1015).
 *
 * mcp-utils 2.9.0's createApiClient throws EdgeBlockedError for an edge's
 * refusal page — a 403 whose message still says "HTTP 403". setlist_healthcheck
 * matched /\b(401|403)\b/ on the message and told the user to check
 * SETLIST_API_KEY, though the key never reached setlist.fm. These run the REAL
 * client against CloudFront's block page.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time. " +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function respond(status: number, body: string, headers: Record<string, string>): Response {
  return new Response(body, { status, headers });
}

async function healthcheck(client: SetlistClient): Promise<Record<string, unknown>> {
  const h = await createTestHarness((server) => registerUtilityTools(server, client));
  const res = (await h.callTool('setlist_healthcheck', {})) as { content: { text: string }[] };
  await h.close();
  return JSON.parse(res.content[0].text) as Record<string, unknown>;
}

describe('setlist_healthcheck on a CDN/WAF block', () => {
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
  });

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('reports the block, not a rejected key', async () => {
    fetchMock.mockImplementation(async () =>
      respond(403, CLOUDFRONT_BLOCK, {
        'content-type': 'text/html',
        'x-cache': 'Error from cloudfront',
      }),
    );

    const r = await healthcheck(new SetlistClient({ apiKey: 'test-key' }));

    expect(r.ok).toBe(false);
    expect(r.edge_blocked).toBe(true);
    expect(String(r.hint)).not.toMatch(/key was rejected/);
    expect(String(r.hint)).toMatch(/CDN|WAF|CloudFront/);
  });

  it('control: a JSON 403 from setlist.fm is still a rejected key', async () => {
    fetchMock.mockImplementation(async () =>
      respond(403, JSON.stringify({ code: 403, message: 'Forbidden' }), {
        'content-type': 'application/json',
      }),
    );

    const r = await healthcheck(new SetlistClient({ apiKey: 'test-key' }));

    expect(r.ok).toBe(false);
    expect(r.edge_blocked).toBeUndefined();
    expect(String(r.hint)).toMatch(/key was rejected/);
  });
});
